---
okd_version: 4.11.0-0.okd-2022-07-29-154152
ignition_version: v2.14.0

# The full domain is <cluster_name>.<base_domain> (e.g. okd4.example.com)
base_domain: example.com
cluster_name: okd4

# opt_out_of_remote_health_reporting: true

# 'true' means that the control plane nodes will also run standard pods
use_control_plane_nodes_for_compute: false

# This public ssh key will be required to access the control plane nodes and worker nodes.
ssh_public_key_file: ~/.ssh/id_ansible.pub

# use_disconnected_registry: true
# disconnected_registry_trust_bundle_file: ./example.crt
# disconnected_registry_qyay_io: registry.example.com:5000/openshift
# disconnected_registry_registry_access_redhat_com: registry.example.com:5000/redhat
# disconnected_registry_registry_redhat_io: registry.example.com:5000/redhat

# use_custom_container_registry: true
# custom_container_registry_ca_file: ./example.crt
# custom_container_registry_hostname_port: registry.example.com:5000

#
# Infra Configuration
#

# Configure UFW port openings for nginx
# configure_ufw: true

#
# Post Installation Configuration
#

# use_cluster_proxy: true
# cluster_proxy_http_proxy: http://proxy.example.com:6080
# cluster_proxy_https_proxy: http://proxy.example.com:6080
# cluster_proxy_no_proxy: internal.example.com,192.168.0.0/24
# cluster_proxy_readiness_endpoints:
#   - http://www.google.com
#   - https://www.google.com

# cluster_admins:
#   - example_user_1
#   - example_user_2

# nfs_server: 192.168.60.20

# compliance_operator: true

# Ansible configuration
ansible_ssh_private_key_file: ~/.ssh/id_ansible
ansible_python_interpreter: auto
