---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
provisioner:
  name: ansible
  options:
    v: true
  inventory:
    links:
      hosts: ../../inventories/local/hosts.yml
      group_vars: ../../inventories/local/group_vars/
verifier:
  name: ansible
