apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: config-masters-autosize-reserved
spec:
  autoSizingReserved: true
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/master: ""
