---
okd_version: 4.11.0-0.okd-2023-01-14-152430
ignition_version: v2.14.0

# The full domain is <cluster_name>.<base_domain> (e.g. okd4.example.com)
base_domain: example.com
cluster_name: okd4

opt_out_of_remote_health_reporting: true

# 'true' means that the control plane nodes will also run standard pods
use_control_plane_nodes_for_compute: true

# This public ssh key will be required to access the control plane nodes and worker nodes.
ssh_public_key_file: ~/.ssh/id_ansible.pub

# use_cluster_proxy: true
# cluster_proxy_http_proxy: http://proxy.example.com:6080
# cluster_proxy_https_proxy: http://proxy.example.com:6080
# cluster_proxy_no_proxy: internal.example.com,192.168.0.0/24

use_disconnected_registry: true
disconnected_registry_trust_bundle_file: "{{ playbook_dir }}/openshift-ca/ca.pem"
disconnected_registry_quay_io_openshift_okd: registry.okd4.example.com:5011/openshift/okd
disconnected_registry_quay_io_openshift_okd_content: registry.okd4.example.com:5011/openshift/okd-content

# use_custom_container_registry: true
# custom_container_registry_ca_file: "{{ playbook_dir }}/example.crt"
# custom_container_registry_hostname_port: registry.example.com:5000

#
# Infra Configuration
#

# Configure UFW port openings for nginx
# configure_ufw: true

#
# Cluster Configuration
#

# disable_default_operator_hub: true

# additional_repository_mirrors:
#   - source: docker.io
#     mirrors:
#       - registry.example.com:5000

nfs_server: 192.168.60.20

argocd: true
argocd_namespace: argocd
argocd_operator_starting_cluster_service_version: v0.4.0
argocd_repository: https://github.com/smuda/home-cluster-argo.git
argocd_repository_revision: main
argocd_sync_wave_delay: 60

# Sealed secrets
sealed_secrets: true
sealed_secret_secret: "{{ playbook_dir }}/sealed-secrets-secret.yml"

#
# Ansible configuration
#

ansible_ssh_private_key_file: ~/.ssh/id_ansible
ansible_python_interpreter: auto
