---
# https://github.com/okd-project/okd/releases
okd_version: 4.13.0-0.okd-2023-09-30-084937
# last 4.12 version: 4.12.0-0.okd-2023-04-16-041331

# Retrieve the beta image from https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/#4.13.0-0.okd
# okd_tools_image_override: quay.io/okd/scos-release:4.12.0-0.okd-scos-2023-02-14-060109

ignition_validate_version: v2.15.0
sops_version: v3.8.1

# The full domain is <cluster_name>.<base_domain> (e.g. okd4.example.com)
base_domain: example.com
cluster_name: okd4

opt_out_of_remote_health_reporting: true

# 'true' means that the control plane nodes will also run standard pods
use_control_plane_nodes_for_compute: true

# This public ssh key will be required to access the control plane nodes and worker nodes.
ssh_public_key_file: ~/.ssh/id_ansible.pub

# use_cluster_proxy: true
# cluster_proxy_http_proxy: http://proxy.example.com:6080
# cluster_proxy_https_proxy: http://proxy.example.com:6080
# cluster_proxy_no_proxy: internal.example.com,192.168.0.0/24

use_disconnected_registry: true
disconnected_registry_trust_bundle_file: "{{ playbook_dir }}/openshift-ca/ca.pem"
disconnected_registries:
  - source: quay.io/openshift/okd
    mirrors:
      - registry.okd4.example.com:5011/openshift/okd
  - source: quay.io/openshift/okd-content
    mirrors:
      - registry.okd4.example.com:5011/openshift/okd-content

# use_custom_container_registry: true
# custom_container_registry_ca_file: "{{ playbook_dir }}/example.crt"
# custom_container_registry_hostname_port: registry.example.com:5000

#
# Local Configuration
#

# Override tool download urls if using a local proxy
# openshift_client_base_url: https://github.com/okd-project/okd/releases/download
# openshift_client_download_url: https://github.com/okd-project/okd/releases/download/{{ okd_version }}/openshift-client-mac-{{ okd_version }}.tar.gz
# openshift_installer_base_url: https://github.com/okd-project/okd/releases/download
# openshift_installer_download_url: https://github.com/okd-project/okd/releases/download/{{ okd_version }}/openshift-install-mac-{{ okd_version }}.tar.gz
# ignition_validate_base_url: https://github.com/coreos/ignition/releases/download
# ignition_validate_download_url: https://github.com/coreos/ignition/releases/download/v2.16.2/ignition-validate-x86_64-apple-darwin
# sops_base_url: https://github.com/getsops/sops/releases/download
# sops_download_url: https://github.com/getsops/sops/releases/download/{{ sops_version }}/sops-{{ sops_version }}.darwin.amd64

#
# Infra Configuration
#

# Use HAProxy for load balancing
loadbalancer_use_haproxy: true

# Configure HAProxy stats login
# haproxy_stats_username: admin
# haproxy_stats_password: password

# Configure network booting for nodes
# network_boot_enabled: true

# Configure UFW port openings for load balancer
# configure_ufw: true

#
# Cluster Configuration
#

# okd_disable_default_operator_catalog_sources: true
# okd_additional_operator_catalog_sources:
#   - name: community-operators-mirror
#     image: registry.access.redhat.com/redhat/community-operator-index:v4.12

# additional_repository_mirrors:
#   - source: docker.io
#     mirrors:
#       - registry.example.com:5000

# network_use_vlan: true
# network_vlan_id:  42
# network_if_name:  eno1

argocd: true
argocd_namespace: argocd
argocd_operator_starting_cluster_service_version: v0.5.0
argocd_repository: https://github.com/smuda/home-cluster-argo.git
argocd_repository_revision: main
argocd_sync_wave_delay: 60
# Enable this once we are running argocd 2.6
# argocd_enable_label_management: "true"

# Sealed secrets
sealed_secrets: true
sealed_secret_secret: "{{ playbook_dir }}/sealed-secrets-secret.yml"

#
# Ansible configuration
#

ansible_ssh_private_key_file: ~/.ssh/id_ansible
ansible_python_interpreter: auto
