---
- name: Publish install version as fact
  ansible.builtin.set_fact:
    okd_version_full: "{{ okd_version | regex_search('[0-9]\\.[0-9]+\\.[0-9]+.*') }}"
    okd_version: "{{ okd_version | regex_search('[0-9]\\.[0-9]+\\.[0-9]+') }}"
    okd_version_minor: "{{ okd_version | regex_search('([0-9]+\\.[0-9]+)\\.', '\\1') | first }}"

- name: Wait for cluster to be stable
  ansible.builtin.shell:
    cmd: >-
      KUBECONFIG="{{ openshift_files_kubeconfig }}"
      "{{ openshift_client_executable }}"
      adm wait-for-stable-cluster --minimum-stable-period=60s
    executable: /bin/bash
  delegate_to: localhost
  register: install_complete
  become: false
  when: okd_version_minor not in ["4.12"]
  changed_when: false
  until: install_complete.rc == 0
