---

#  https://docs.okd.io/4.15/operators/admin/olm-restricted-networks.html
- name: Disable default OperatorHub sources
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: OperatorHub
      metadata:
        name: cluster
      spec:
        disableAllDefaultSources: true
        sources:
          - disabled: "{{ okd_disable_certified_operators }}"
            name: certified-operators
          - disabled: "{{ okd_disable_community_operators }}"
            name: community-operators
          - disabled: "{{  okd_disable_redhat_marketplace }}"
            name: redhat-marketplace
          - disabled: "{{ okd_disable_redhat_operators }}"
            name: redhat-operators
  register: status
  until: "'result' in status"
  when: okd_disable_default_operator_catalog_sources

- name: Configure additional operator catalog sources
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    template: templates/catalog-source.yaml.j2
  when: okd_additional_operator_catalog_sources | length > 0
  with_items: "{{ okd_additional_operator_catalog_sources }}"
