# https://docs.okd.io/latest/nodes/nodes/nodes-nodes-resources-configuring.html

- name: 5 Wait for existing machine config pools to stabilize
  ansible.builtin.command:
    cmd: |
      "{{ openshift_client_executable }}"
      --kubeconfig "{{ openshift_files_kubeconfig }}"
      wait mcp/master --for condition=updated --timeout=1800s
  register: mcp_status
  until: mcp_status.rc == 0
  retries: 6000
  delay: 1 # pause for # sec b/w each call
  changed_when: false

- name: 5.1 Pause machine configs
  ansible.builtin.shell: |
    KUBECONFIG="{{ openshift_files_kubeconfig }}" \
    "{{ openshift_client_executable }}" patch --type=merge --patch='{ "spec": { "paused": true } }' machineconfigpool/master
  changed_when: true

- name: 5.2 Apply machine configs
  ansible.builtin.shell: |
    KUBECONFIG="{{ openshift_files_kubeconfig }}" \
    "{{ openshift_client_executable }}" apply -f \
    {{ item }}
  with_fileglob:
    - ../templates/5-machine-config/*.yaml
  register: machineconfig
  changed_when: '"unchanged" not in machineconfig.stdout'

- name: 5.3 Unpause machine configs
  ansible.builtin.shell: |
    KUBECONFIG="{{ openshift_files_kubeconfig }}" \
    "{{ openshift_client_executable }}" patch --type=merge --patch='{ "spec": { "paused": false } }' machineconfigpool/master
  changed_when: true

- name: 5.4 Wait for machine config to update
  ansible.builtin.command:
    cmd: |
      "{{ openshift_client_executable }}"
      --kubeconfig "{{ openshift_files_kubeconfig }}"
      wait mcp/master --for condition=updated --timeout=1800s
  register: mcp_status
  until: mcp_status.rc == 0
  retries: 6000
  delay: 1 # pause for # sec b/w each call
  changed_when: false
