- hosts: localhost
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: Make sure module kubernetes.core is installed and up to date
      ansible.builtin.shell:
        cmd: ansible-galaxy collection install kubernetes.core
      delegate_to: localhost
    - name: Make sure module community.general is installed and up to date
      ansible.builtin.shell:
        cmd: ansible-galaxy collection install community.general
      delegate_to: localhost
