- hosts: localhost
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: make sure module community.kubernetes is installed
      ansible.builtin.shell:
        cmd: ansible-galaxy collection install community.kubernetes
      delegate_to: localhost
