---
#
# Configure OKD cluster
#

- name: Configure cluster
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  roles:
    # First wait for cluster to be ready
    - role: okd_wait_for_cluster_ready
    # Then perform any additional configurations
    - role: okd_operator_catalog_sources
    - role: okd/additional_repository_mirrors
    # Install Argo CD
    - role: argocd
