---
#
# Configure OKD cluster
#

- name: Configure cluster
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  roles:
    # First wait for cluster to be ready
    - role: okd_wait_for_cluster_ready
    # Then perform any additional configurations
    - role: okd_operator_catalog_sources
    - role: okd_additional_repository_mirrors
    - role: okd_issue_pending_certificates
    # Make sure cluster is stable before installing application in it
    - role: okd_wait_for_cluster_stable
    # Install Argo CD
    - role: argocd
