---
- hosts: rpis
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: setup-rpi
      become: true

- hosts: lbs
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: lbs_dnsmasq_local
      become: true
      when: (local_install is defined) and local_install
    - role: lbs_install
      become: true
    - role: lbs_ignition_files
      become: true
    - role: lbs_loadbalancer
      become: true
      vars:
        bootstrap_enabled: true
