- hosts: rpis
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: setup-rpi
      become: true

- hosts: lbs
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: nginx-ignition-files
      become: true
    - role: nginx-loadbalancer
      become: true
      vars:
        bootstrap_enabled: true
