---
- name: Create RPi
  hosts: rpis
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: setup-rpi
      become: true

- name: Create lbs
  hosts: lbs
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: lbs_dnsmasq_local
      become: true
      when: (local_install is defined) and local_install
    - role: lbs_install
      become: true
