---

- name: Install local tools
  ansible.builtin.import_playbook: install-local-tools.yml

- name: Create local files
  ansible.builtin.import_playbook: create-local-files.yml

- name: Validate DNS
  ansible.builtin.import_playbook: validate-dns.yml

- name: Create lbs
  ansible.builtin.import_playbook: create-lbs.yml

- name: Configure lbs ignition files
  ansible.builtin.import_playbook: configure-lbs-ignition-files.yml
  when: not openshift_agent_installation

- name: Configure lbs network boot
  ansible.builtin.import_playbook: configure-lbs-network-boot.yml

- name: Configure lbs bootstrap enabled
  ansible.builtin.import_playbook: configure-lbs-bootstrap-enabled.yml

- name: Wait for installation
  ansible.builtin.import_playbook: wait-for-installation.yml

- name: Configure lbs bootstrap disabled
  ansible.builtin.import_playbook: configure-lbs-bootstrap-disabled.yml

- name: Wait for workers
  ansible.builtin.import_playbook: wait-for-workers.yml
  when: not openshift_agent_installation | default(true)

- name: Configure cluster
  ansible.builtin.import_playbook: configure-cluster.yml

- name: Roll the cluster certificates
  ansible.builtin.import_playbook: roll-cluster-certificates.yml
