- hosts: all
  any_errors_fatal: true
  gather_facts: no

- import_playbook: 0-create-local-files.yml
  vars:
    hosts: all

- import_playbook: 1-create-infra1.yml
  vars:
    hosts: all

- import_playbook: 2-wait-for-installation.yml
  vars:
    hosts: all

- import_playbook: 3-remove-bootstrap-from-infra.yml
  vars:
    hosts: all

- import_playbook: 4-post-installation.yml
  vars:
    hosts: all
