---

- hosts: all
  any_errors_fatal: true
  gather_facts: false

- ansible.builtin.import_playbook: install-ansible-dependencies.yml

- ansible.builtin.import_playbook: create-local-files.yml

- ansible.builtin.import_playbook: validate-dns.yml

- ansible.builtin.import_playbook: create-lbs.yml

- ansible.builtin.import_playbook: wait-for-installation.yml

- ansible.builtin.import_playbook: remove-bootstrap-from-infra.yml

- ansible.builtin.import_playbook: wait-for-workers.yml

- ansible.builtin.import_playbook: configure-cluster.yml

- ansible.builtin.import_playbook: post-installation.yml
