- hosts: all
  any_errors_fatal: true
  gather_facts: false

- ansible.builtin.import_playbook: install-ansible-dependencies.yml
  vars:
    hosts: localhost

- ansible.builtin.import_playbook: create-local-files.yml
  vars:
    hosts: all

- ansible.builtin.import_playbook: validate-dns.yml
  vars:
    hosts: all

- ansible.builtin.import_playbook: 1-create-infra1.yml
  vars:
    hosts: all

- ansible.builtin.import_playbook: 2-wait-for-installation.yml
  vars:
    hosts: all

- ansible.builtin.import_playbook: 3-remove-bootstrap-from-infra.yml
  vars:
    hosts: all

- ansible.builtin.import_playbook: 3-wait-for-workers.yml
  vars:
    hosts: all

- ansible.builtin.import_playbook: 4-post-installation.yml
  vars:
    hosts: all
