---

collections:
  - name: kubernetes.core
    version: 2.4.0
    source: https://galaxy.ansible.com
  - name: community.general
    version: 6.5.0
    source: https://galaxy.ansible.com
  - name: community.sops
    version: 1.6.6
    source: https://galaxy.ansible.com
