---
#
# Roll the cluster certificates
#

- name: Roll the cluster certificates
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  roles:
    # Make sure cluster is stable before rolling cluster certificates
    - role: okd_wait_for_cluster_stable
    # Roll cluster certificates
    - role: okd_roll_cluster_certificate
