---
- name: Wait for installation
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: wait_for_installation
      vars:
        wait_for_installation_skip_coreos_iso_prompt: "{{ network_boot_enabled | default(false) | bool }}"
