---
- name: Wait for installation
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: wait_for_installation
      vars:
        wait_for_installation_show_coreos_iso_prompt: "{{ not(network_boot_enabled) }}"
