---

- name: Get install version
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail &&
      "{{ openshift_install_executable }}" version | head -1
    executable: /bin/bash
  delegate_to: localhost
  register: install_version_cmd
  changed_when: false

- name: Publish install version as fact
  ansible.builtin.set_fact:
    okd_version_full: "{{ install_version_cmd.stdout | regex_search('[0-9]\\.[0-9]+\\.[0-9]+.*') }}"
    okd_version: "{{ install_version_cmd.stdout | regex_search('[0-9]\\.[0-9]+\\.[0-9]+') }}"
    okd_version_minor: "{{ install_version_cmd.stdout | regex_search('([0-9]+\\.[0-9]+)\\.', '\\1') | first }}"

- name: Log oc version
  ansible.builtin.debug:
    msg:
      - "okd_version_full: {{ okd_version_full }}"
      - "okd_version: {{ okd_version }}"
      - "okd_version_minor: {{ okd_version_minor }}"
