# https://docs.openshift.com/container-platform/4.8/authentication/identity_providers/configuring-github-identity-provider.html
- name: 2.1 Set variables
  ansible.builtin.set_fact:
    ghsecretname: "github-client-secret"
    ghtempfile: "./tmp-github-cluster-config.yaml"

- name: 2.1 Display the JSON file content
  ansible.builtin.shell: cat {{ ghconfigfilename }}
  register: ghconfigfile

- name: save the Json data to a Variable as a Fact
  ansible.builtin.set_fact:
    ghconfig: "{{ ghconfigfile.stdout | from_json }}"

- name: Log ghconfig
  ansible.builtin.debug:
    var: ghconfig

- name: Validate ghconfig format
  ansible.builtin.fail:
    msg: "Check your github configuration file"
  when: ghconfig.clientID is not defined or ghconfig.clientID == "" or ghconfig.clientSecret is not defined or ghconfig.clientSecret == ""

- name: Log ghconfig.clientID
  ansible.builtin.debug:
    var: ghconfig.clientID

- name: Log ghconfig.clientSecret
  ansible.builtin.debug:
    var: ghconfig.clientSecret

- name: Log ghconfig.organizations
  ansible.builtin.debug:
    var: ghconfig.organizations

- name: 2.1 If secret already exist, delete
  ansible.builtin.shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    "{{ openshift_client_executable }}" \
    -n openshift-config \
    delete secret {{ ghsecretname }} \
    --ignore-not-found
  register: result
  changed_when: result.stdout == "secret \"github-client-secret\" deleted"

- name: 2.1 Add github secret
  ansible.builtin.shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    "{{ openshift_client_executable }}" \
    -n openshift-config \
    create secret generic {{ ghsecretname }} \
    --from-literal=clientSecret='{{ ghconfig.clientSecret }}'
  register: ocresult
  changed_when: '"unchanged" not in ocresult.stdout'

- name: 2.1 Create temporary file
  ansible.builtin.template:
    src: templates/2-oauth/cluster.yaml
    dest: "{{ ghtempfile }}"

- name: 2.1. Add github as oauth provider
  ansible.builtin.shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    "{{ openshift_client_executable }}" \
    apply -f {{ ghtempfile }}
  register: patchoutput
  changed_when:
    - patchoutput.stdout != "clusterversion.config.openshift.io/version patched (no change)"
    - patchoutput.stdout != "oauth.config.openshift.io/cluster unchanged"

- name: 2.1 Delete temporary file
  ansible.builtin.file:
    path: "{{ ghtempfile }}"
    state: absent
