- name: 3. {{ item }} Create directory ./tmp
  ansible.builtin.file:
    state: directory
    path: ./tmp
    mode: '0755'

- name: 3. {{ item }} Check if cluster admin already exists
  ansible.builtin.shell: |
    set -o pipefail && \
    KUBECONFIG="{{ openshift_files_kubeconfig }}" \
    "{{ openshift_client_executable }}" \
    get clusterrolebinding -o json \
    | jq --raw-output \
    '.items[] | select(.roleRef.name == "cluster-admin") | select(.subjects[].kind=="User") | select(.subjects[].name == "{{ item }}") | .metadata.name'
  register: result
  changed_when: false

- name: 3. {{ item }} Render template Add cluster admin
  ansible.builtin.template:
    src: templates/3-cluster-admin.yaml
    dest: ./tmp/cluster-admin.yaml
    mode: '0644'
  when: result.stdout == ""

- name: 3. {{ item }} Add cluster admin
  ansible.builtin.shell: |
    KUBECONFIG="{{ openshift_files_kubeconfig }}" \
    "{{ openshift_client_executable }}" \
    apply -f ./tmp/cluster-admin.yaml
  when: result.stdout == ""

- name: 3. {{ item }} Remove temporary file
  ansible.builtin.file:
    state: absent
    path: ./tmp/cluster-admin.yaml
