# https://docs.okd.io/latest/nodes/nodes/nodes-nodes-resources-configuring.html

- name: 5 Get cluster version
  shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    ./openshift-client/oc version -o json | jq --raw-output '.openshiftVersion'
  register: okd_version

- name: 5 Apply machine configs
  shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    ./openshift-client/oc apply -f \
    {{ item }}
  with_fileglob:
    - ../templates/5-machine-config/*.yaml
  register: machineconfig
  changed_when: '"unchanged" not in machineconfig.stdout'
