# https://docs.okd.io/latest/nodes/nodes/nodes-nodes-resources-configuring.html

- name: 5 Get cluster version
  ansible.builtin.shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    ./openshift-client/oc version -o json | jq --raw-output '.openshiftVersion'
  register: okd_version

- name: 5.1 Pause machine configs
  ansible.builtin.shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    ./openshift-client/oc patch --type=merge --patch='{"spec":{"paused":true}}' machineconfigpool/master

- name: 5.2 Apply machine configs
  ansible.builtin.shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    ./openshift-client/oc apply -f \
    {{ item }}
  with_fileglob:
    - ../templates/5-machine-config/*.yaml
  register: machineconfig
  changed_when: '"unchanged" not in machineconfig.stdout'

- name: 5.3 Unpause machine configs
  ansible.builtin.shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    ./openshift-client/oc patch --type=merge --patch='{"spec":{"paused":false}}' machineconfigpool/master

- name: 5.4 Wait for machine config to update
  ansible.builtin.shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    ./openshift-client/oc wait mcp/master --for condition=updated
