- name: 5.1 Verify failed machine configs
  shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    ./openshift-client/oc get mcp master -o json | jq '.status.degradedMachineCount'
  register: degraded_machine_count

- set_fact:
    nrOfMasters: "{{ groups['masters'] | length }}"

- debug:
    var: nrOfMasters

- fail:
  when: nrOfMasters == degraded_machine_count.stdout

- name: 5.1 Delete failed machine configs
  shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    ./openshift-client/oc delete mc 99-okd-master-disable-mitigations
  when: nrOfMasters == degraded_machine_count.stdout

- name: 5.1 Delete failed machine configs
  shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    ./openshift-client/oc delete mc 99-master-okd-extensions
  when: nrOfMasters == degraded_machine_count.stdout
