- name: 6.1 Create or update the catalog source
  kubernetes.core.k8s:
    kubeconfig: ./openshift-files/auth/kubeconfig
    resource_definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        name: compliance-operator
        namespace: openshift-marketplace
      spec:
        displayName: Compliance Operator Upstream
        publisher: github.com/openshift/compliance-operator
        sourceType: grpc
        image: quay.io/compliance-operator/compliance-operator-index:latest

- name: 6.2 Create or update namespace openshift-compliance
  kubernetes.core.k8s:
    kubeconfig: ./openshift-files/auth/kubeconfig
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-compliance
        annotations:
          openshift.io/node-selector: ""

- name: 6.3 Create or update operator-group
  kubernetes.core.k8s:
    kubeconfig: ./openshift-files/auth/kubeconfig
    resource_definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: compliance-operator
        namespace: openshift-compliance
      spec:
        targetNamespaces:
          - openshift-compliance

- name: 6.4 Create or update subscription
  kubernetes.core.k8s:
    kubeconfig: ./openshift-files/auth/kubeconfig
    resource_definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: compliance-operator-sub
        namespace: openshift-compliance
      spec:
        channel: "alpha"
        installPlanApproval: Automatic
        name: compliance-operator
        source: compliance-operator
        sourceNamespace: openshift-marketplace

- name: 6.5 Wait for operator to start
  shell: |
    KUBECONFIG=./openshift-files/auth/kubeconfig \
    ./openshift-client/oc \
    -n openshift-compliance \
    get deployment compliance-operator -o json \
    | jq '.status.readyReplicas'
  register: readyReplicas
  retries: 60
  delay: 5
  until: readyReplicas.stdout == "1"

- name: 6.6 Bind scanning type "default" to profiles to initiate scanning
  kubernetes.core.k8s:
    kubeconfig: ./openshift-files/auth/kubeconfig
    resource_definition:
      apiVersion: compliance.openshift.io/v1alpha1
      kind: ScanSettingBinding
      metadata:
        name: cis-compliance
        namespace: openshift-compliance
      profiles:
        - name: ocp4-cis-node
          kind: Profile
          apiGroup: compliance.openshift.io/v1alpha1
        - name: ocp4-cis
          kind: Profile
          apiGroup: compliance.openshift.io/v1alpha1
      settingsRef:
        #name: default
        name: default-auto-apply
        kind: ScanSetting
        apiGroup: compliance.openshift.io/v1alpha1
