- name: 7.1 Create or update subscription
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    resource_definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        labels:
          operators.coreos.com/argocd-operator.openshift-operators: ""
        name: argocd-operator
        namespace: openshift-operators
      spec:
        channel: alpha
        installPlanApproval: Automatic
        name: argocd-operator
        source: community-operators
        sourceNamespace: openshift-marketplace
        startingCSV: argocd-operator.v0.3.0
        config:
          env:
            - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
              value: argocd

- name: 7.2 Wait for operator to start
  ansible.builtin.shell: |
    set -o pipefail && \
    KUBECONFIG="{{ openshift_files_kubeconfig }}" \
    "{{ openshift_client_executable }}" \
    -n openshift-operators \
    get deploy argocd-operator-controller-manager -o json \
    | jq '.status.readyReplicas'
  register: ready_replicas
  retries: 60
  delay: 5
  until: ready_replicas.stdout == "1"
  changed_when: false

- name: 7.3 Create or update namespace argocd
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd
        annotations:
          openshift.io/node-selector: ""

- name: 7.4 Setup a basic ArgoCD cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    resource_definition:
      apiVersion: argoproj.io/v1alpha1
      kind: ArgoCD
      metadata:
        name: argocd
        namespace: argocd
      spec:
        dex:
          openShiftOAuth: true
          groups:
            - "system:authenticated"
        server:
          route:
            enabled: true
        rbac:
          defaultPolicy: 'role:readonly'
          policy: |
            g, cluster-admins, role:admin
            g, system:authenticated, role:admin
          scopes: '[groups]'

- name: 7.5 Create or update the namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    resource_definition:
      kind: Namespace
      apiVersion: v1
      metadata:
        name: argo-apps


- name: 7.6 Initiate applications from github
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: github-smuda
        namespace: argocd
        labels:
          argocd.argoproj.io/secret-type: repository
      stringData:
        type: git
        url: https://github.com/smuda/home-cluster-argo.git


- name: 7.7 Initiate applications from github
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    resource_definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: argo-apps
        namespace: argocd
        finalizers:
          - resources-finalizer.argocd.argoproj.io
      spec:
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: default
        source:
          helm:
            version: v3
            releaseName: argo-apps
            valueFiles:
              - values-okd.yaml
          path: start/
          repoURL: https://github.com/smuda/home-cluster-argo.git
          targetRevision: main
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            selfHeal: true
          preserveResourcesOnDeletion: false
