# Pathing update stream is no longer needed in 4.9+.
# Keeping this here if it's needed later.
# - ansible.builtin.include_tasks: "1-patch-update-stream.yml"

- ansible.builtin.include_tasks: "1-cluster-proxy.yml"

- ansible.builtin.include_tasks: "2.0-oauth.yml"

- ansible.builtin.include_tasks: "3-cluster-admin.yml"
  loop: "{{ cluster_admins }}"
  when: cluster_admins is defined

- ansible.builtin.include_tasks: "4-nfs-storage.yml"

- ansible.builtin.include_tasks: "5-machine-config.yml"

- ansible.builtin.include_tasks: "6-compliance-operator.yml"
  when:
    - compliance_operator is defined

- ansible.builtin.include_tasks: "7-argocd.yml"
  when:
    - argocd is defined
