- include_tasks: "1-patch-update-stream.yml"

- include_tasks: "2.0-oauth.yml"

- include_tasks: "3-cluster-admin.yml"
  with_items:
    - smuda
    - OscarAyoy

- name: Pause for 20 minutes to let cluster stabilize
  pause:
    minutes: 20

- include_tasks: "4-machine-config.yml"

