- name: Check if config file exists
  ansible.builtin.stat:
    path: "sealed-secrets-secret.yml"
  register: secret_stat

- name: File does not exist.
  ansible.builtin.fail:
    msg: "Missing file sealed-secrets-secret.yml with pre-generated secret"
  when:
    - not secret_stat.stat.exists

- name: Install pre-configured secret
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    state: present
    src: "sealed-secrets-secret.yml"
