---
openshift_client_base_url: "https://github.com/openshift/okd/releases/download/{{ okd_version }}"
openshift_installer_base_url: "https://github.com/openshift/okd/releases/download/{{ okd_version }}"
ignition_validate_base_url: "https://github.com/coreos/ignition/releases/download/{{ ignition_validate_version }}"
