---

- name: Copy over nginx loadbalancer configuration
  ansible.builtin.template:
    src: kubernetes.conf
    dest: /etc/nginx/tcpconf.d/kubernetes.conf
    mode: '0644'
  notify: nginx restart

- name: Configure UFW port openings
  ansible.builtin.include_tasks: "ufw.yml"
  when: configure_ufw
