---

- name: Create or update the namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    resource_definition:
      kind: Namespace
      apiVersion: v1
      metadata:
        name: "{{ argocd_namespace }}"

- name: Initiate applications from github
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: github-smuda
        namespace: "{{ argocd_namespace }}"
        labels:
          argocd.argoproj.io/secret-type: repository
      stringData:
        type: git
        url: "{{ argocd_repository }}"

- name: Initiate applications from github
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    resource_definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: root
        namespace: "{{ argocd_namespace }}"
        finalizers:
          - resources-finalizer.argocd.argoproj.io
      spec:
        destination:
          namespace: "{{ argocd_namespace }}"
          server: https://kubernetes.default.svc
        project: default
        source:
          helm:
            version: v3
            releaseName: root
            valueFiles:
              - "{{ argocd_value_file }}"
            parameters:
              - name: argo.common.target_revision
                value: "{{ argocd_repository_revision }}"
              - name: argo.common.apps_namespace
                value: "{{ argocd_namespace }}"
              - name: argo.common.enableLabelManagement
                value: "{{ argocd_enable_label_management }}"
          path: _start/
          repoURL: "{{ argocd_repository }}"
          targetRevision: "{{ argocd_repository_revision }}"
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            selfHeal: true
          preserveResourcesOnDeletion: false
