---
- name: Create or update Argo CD Operator subscription
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    resource_definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        labels:
          operators.coreos.com/argocd-operator.openshift-operators: ""
        name: argocd-operator
        namespace: openshift-operators
      spec:
        channel: alpha
        installPlanApproval: Manual
        name: argocd-operator
        source: community-operators
        sourceNamespace: openshift-marketplace
        startingCSV: argocd-operator.{{ argocd_operator_starting_cluster_service_version }}
        config:
          env:
            - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
              value: "{{ argocd_namespace }}"

- name: Wait for ArgoCD installplan
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      KUBECONFIG="{{ openshift_files_kubeconfig }}" \
      "{{ openshift_client_executable }}" \
      -n openshift-operators \
      get installplan -o json | \
      jq -r '.items[] | select(.spec.clusterServiceVersionNames[] == "argocd-operator.{{ argocd_operator_starting_cluster_service_version }}") | .metadata.name'
    executable: /bin/bash
  register: installplan_names
  retries: 60
  delay: 5
  until: installplan_names.stdout != ""
  changed_when: false

- name: Approve the installplan
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      KUBECONFIG="{{ openshift_files_kubeconfig }}" \
      "{{ openshift_client_executable }}" \
      -n openshift-operators \
      patch installplan {{ installplan_names.stdout }} \
      --type merge \
      --patch '{"spec": {"approved": true }}'
    executable: /bin/bash
  changed_when: true

- name: Wait for Argo CD Operator to start
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      KUBECONFIG="{{ openshift_files_kubeconfig }}" \
      "{{ openshift_client_executable }}" \
      -n openshift-operators \
      get deploy argocd-operator-controller-manager -o json \
      | jq '.status.readyReplicas'
    executable: /bin/bash
  register: ready_replicas
  retries: 60
  delay: 5
  until: ready_replicas.stdout == "1"
  changed_when: false

- name: Create or update namespace {{ argocd_namespace }}
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ argocd_namespace }}"
        annotations:
          openshift.io/node-selector: ""

- name: Setup a basic Argo CD cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_files_kubeconfig }}"
    resource_definition:
      apiVersion: argoproj.io/v1alpha1
      kind: ArgoCD
      metadata:
        name: argocd
        namespace: "{{ argocd_namespace }}"
      spec:
        applicationSet:
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
        controller:
          resources:
            limits:
              memory: 2500Mi
            requests:
              cpu: 250m
              memory: 1500Mi
          sharding:
            enabled: true
            replicas: 2
        ha:
          enabled: true
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
        sso:
          provider: dex
          dex:
            openShiftOAuth: true
            groups:
              - "system:authenticated"
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 250m
                memory: 128Mi
        server:
          autoscale:
            enabled: true
            hpa:
              maxReplicas: 3
              minReplicas: 2
              scaleTargetRef:
                apiVersion: apps/v1
                kind: Deployment
                name: argocd-server
          env:
            - name: ARGOCD_SYNC_WAVE_DELAY
              value: "{{ argocd_sync_wave_delay | default('2') }}"
          route:
            enabled: true
          resources:
            limits:
              memory: 321Mi
            requests:
              cpu: 125m
              memory: 224Mi
        prometheus:
          enabled: true
          ingress:
            enabled: false
          route:
            enabled: false
        rbac:
          defaultPolicy: 'role:readonly'
          policy: |
            g, cluster-admins, role:admin
            g, system:authenticated, role:admin
          scopes: '[groups]'
        redis:
          image: registry.okd4.example.com:5010/library/redis
          resources:  # This is only used if ha.enabled is false
            limits:
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
        repo:
          replicas: 2
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
        cm:
          resource.customizations: |
            argoproj.io/Application:
              health.lua: |
                hs = {}
                hs.status = "Progressing"
                hs.message = ""
                if obj.status ~= nil then
                  if obj.status.health ~= nil then
                    hs.status = obj.status.health.status
                    if obj.status.health.message ~= nil then
                      hs.message = obj.status.health.message
                    end
                  end
                end
                return hs
