---
- name: Configure sealed secrets
  ansible.builtin.include_tasks: "sealed_secrets.yml"
  when:
    - sealed_secrets is defined

- name: Configure openshift-gitops-operator
  ansible.builtin.include_tasks: "openshift-gitops-operator.yml"
  when:
    - argocd is defined

- name: Configure argocd applications
  ansible.builtin.include_tasks: "argocd-applications.yml"
  when:
    - argocd is defined
