---
- ansible.builtin.import_playbook: ../../create-lbs.yml

- ansible.builtin.import_playbook: ../../configure-lbs-ignition-files.yml

- ansible.builtin.import_playbook: ../../configure-lbs-network-boot.yml

- ansible.builtin.import_playbook: ../../configure-lbs-bootstrap-enabled.yml
