---

- name: Install local tools
  ansible.builtin.import_playbook: ../../install-local-tools.yml

- name: Create local files
  ansible.builtin.import_playbook: ../../create-local-files.yml

- name: Create lbs
  ansible.builtin.import_playbook: ../../create-lbs.yml

- name: Configure lbs ignition files
  ansible.builtin.import_playbook: ../../configure-lbs-ignition-files.yml

- name: Configure lbs network boot
  ansible.builtin.import_playbook: ../../configure-lbs-network-boot.yml

- name: Configure lbs bootstrap enabled
  ansible.builtin.import_playbook: ../../configure-lbs-bootstrap-enabled.yml
