---
- name: Create local install directory
  ansible.builtin.file:
    state: directory
    path: "{{ openshift_install_directory }}"
    mode: '0755'

- name: Define openshift installer download url (OKD)
  when:
    - openshift_installer_download_url is undefined
    - not is_openshift  # This is OKD
  ansible.builtin.set_fact:
    openshift_installer_download_url: "{{ openshift_installer_base_url }}/{{ okd_version }}/openshift-install-{{ okd_tools_arch }}-{{ okd_version }}.tar.gz"  # noqa yaml[line-length]

- name: Define openshift installer download url (OCP)
  when:
    - openshift_installer_download_url is undefined
    - is_openshift  # This is OCP
  ansible.builtin.set_fact:
    openshift_installer_download_url: "{{ openshift_installer_base_url }}/openshift-install-{{ okd_tools_arch }}-{{ okd_version }}.tar.gz"  # noqa yaml[line-length]

- name: Download openshift installer if needed
  ansible.builtin.include_tasks: "download-if-url-changed.yml"
  vars:
    name: Openshift installer
    url: "{{ openshift_installer_download_url }}"
    download_url_file: "{{ openshift_install_directory }}/.openshift-installer.url"
    download_target: "{{ openshift_install_archive }}"
    untar_downloaded: true
    untar_directory: "{{ openshift_install_directory }}"
    delete_download_target: true
