---
- name: Create directory openshift-client
  ansible.builtin.file:
    state: directory
    path: "{{ openshift_client_directory }}"
    mode: '0755'

- name: Download openshift client if needed
  ansible.builtin.include_tasks: "download-if-url-changed.yml"
  vars:
    name: Openshift client
    url: "https://github.com/openshift/okd/releases/download/{{ okd_version }}/openshift-client-{{ okd_tools_arch }}-{{ okd_version }}.tar.gz"  # noqa yaml[line-length]
    download_url_file: "{{ openshift_client_directory }}/.openshift-client.url"
    download_target: "{{ openshift_client_archive }}"
    untar_downloaded: true
    untar_directory: "{{ openshift_client_directory }}"
    delete_download_target: true

- name: Download ignition validate if needed
  ansible.builtin.include_tasks: "download-if-url-changed.yml"
  vars:
    name: Openshift client
    url: "https://github.com/coreos/ignition/releases/download/{{ ignition_version }}/ignition-validate-{{ ignition_tool_arch }}"  # noqa yaml[line-length]
    download_url_file: "{{ openshift_client_directory }}/.ignition-validate.url"
    download_target: "{{ openshift_ignition_validate_executable }}"
    untar_downloaded: false
    untar_directory: "{{ openshift_client_directory }}"
    delete_download_target: false

- name: Chmod ignition validator
  ansible.builtin.file:
    path: "{{ openshift_ignition_validate_executable }}"
    mode: '0755'
