---
- name: Create local install directory
  ansible.builtin.file:
    state: directory
    path: "{{ openshift_install_directory }}"
    mode: '0755'

- name: Download openshift installer if needed
  ansible.builtin.include_tasks: "download-if-url-changed.yml"
  vars:
    name: Openshift installer
    url: "{{ openshift_installer_base_url }}/openshift-install-{{ okd_tools_arch }}-{{ okd_version }}.tar.gz"  # noqa yaml[line-length]
    download_url_file: "{{ openshift_install_directory }}/.openshift-installer.url"
    download_target: "{{ openshift_install_archive }}"
    untar_downloaded: true
    untar_directory: "{{ openshift_install_directory }}"
    delete_download_target: true
