---
#
# OpenShift CLI
#

- name: Create directory openshift-client
  ansible.builtin.file:
    state: directory
    path: "{{ openshift_client_directory }}"
    mode: '0755'

- name: Define openshift client download url (OKD)
  when:
    - openshift_client_download_url is undefined
    - not is_openshift   # This is OKD
  ansible.builtin.set_fact:
    openshift_client_download_url: "{{ openshift_client_base_url }}/{{ okd_version }}/openshift-client-{{ okd_tools_arch }}-{{ okd_version }}.tar.gz"

- name: Define openshift client download url (OCP)
  when:
    - openshift_client_download_url is undefined
    - is_openshift  # This is OCP
  ansible.builtin.set_fact:
    openshift_client_download_url: "{{ openshift_client_base_url }}/openshift-client-{{ okd_tools_arch }}-{{ okd_version }}.tar.gz"

- name: Download openshift client if needed
  ansible.builtin.include_tasks: "download-if-url-changed.yml"
  vars:
    name: Openshift client
    url: "{{ openshift_client_download_url }}"
    download_url_file: "{{ openshift_client_directory }}/.openshift-client.url"
    download_target: "{{ openshift_client_archive }}"
    untar_downloaded: true
    untar_directory: "{{ openshift_client_directory }}"
    delete_download_target: true

#
# Ignition Validate
#

- name: Define ignition validate download url
  when:
    - ignition_validate_download_url is undefined
  ansible.builtin.set_fact:
    ignition_validate_download_url: "{{ ignition_validate_base_url }}/{{ ignition_validate_version }}/ignition-validate-{{ ignition_tool_arch }}"

- name: Download ignition validate if needed
  ansible.builtin.include_tasks: "download-if-url-changed.yml"
  vars:
    name: Openshift client
    url: "{{ ignition_validate_download_url }}"
    download_url_file: "{{ openshift_client_directory }}/.ignition-validate.url"
    download_target: "{{ openshift_ignition_validate_executable }}"
    untar_downloaded: false
    untar_directory: "{{ openshift_client_directory }}"
    delete_download_target: false

- name: Chmod ignition validator
  ansible.builtin.file:
    path: "{{ openshift_ignition_validate_executable }}"
    mode: '0755'

#
# SOPS
#

- name: Define SOPS download url
  when:
    - sops_download_url is undefined
  ansible.builtin.set_fact:
    sops_download_url: "{{ sops_base_url }}/{{ sops_version }}/sops-{{ sops_version }}.{{ sops_arch }}"

- name: Download SOPS if needed
  ansible.builtin.include_tasks: "download-if-url-changed.yml"
  vars:
    name: SOPS
    url: "{{ sops_download_url }}"
    download_url_file: "{{ openshift_client_directory }}/.sops.url"
    download_target: "{{ sops_executable }}"
    untar_downloaded: false
    untar_directory: "{{ openshift_client_directory }}"
    delete_download_target: false

- name: Chmod SOPS
  ansible.builtin.file:
    path: "{{ sops_executable }}"
    mode: '0755'
