---
- name: Gathering facts
  ansible.builtin.setup:

- name: Detect install system is Linux x86_64
  when:
    - ansible_system == "Linux"
    - ansible_architecture == "x86_64"
  ansible.builtin.set_fact:
    supported_arch: true
    okd_tools_arch: linux
    ignition_tool_arch: x86_64-linux
    sops_arch: linux.amd64

- name: Detect install system is MacOS x86_64
  when:
    - ansible_system == "Darwin"
    - ansible_architecture == "x86_64"
  ansible.builtin.set_fact:
    supported_arch: true
    okd_tools_arch: mac
    ignition_tool_arch: x86_64-apple-darwin
    sops_arch: darwin.amd64

- name: Detect install system is MacOS arm64
  when:
    - ansible_system == "Darwin"
    - ansible_architecture == "arm64"
  ansible.builtin.set_fact:
    supported_arch: true
    okd_tools_arch: mac-arm64
    ignition_tool_arch: aarch64-apple-darwin
    sops_arch: darwin.arm64

- name: Fail if architecture is not supported
  when: supported_arch is not defined
  ansible.builtin.fail:
    msg: "Aborting. System [{{ ansible_system }}] and architecture [{{ ansible_architecture }}] is not supported at the moment."

- name: Download other tools
  ansible.builtin.include_tasks: "download-tools.yml"

- name: Download openshift-installer
  ansible.builtin.include_tasks: "download-installer.yml"
  when: okd_tools_image_override is not defined

- name: Extract openshift-installer from image
  ansible.builtin.include_tasks: "extract-installer.yml"
  when: okd_tools_image_override is defined
