---

- name: Create installation config
  ansible.builtin.template:
    src: templates/install-config.yaml
    dest: "{{ openshift_files_directory }}/install-config.yaml"
    mode: '0644'

- name: Create cluster manifests files
  ansible.builtin.command:
    cmd: "{{ openshift_install_executable }} create manifests --dir={{ openshift_files_directory }}"
  changed_when: false

- name: Create cluster ignition files
  ansible.builtin.command:
    cmd: "{{ openshift_install_executable }} create ignition-configs --dir={{ openshift_files_directory }}"
  changed_when: false
