---
- ansible.builtin.include_tasks: "config-dir.yml"
- ansible.builtin.include_tasks: "pull-secret.yml"
- ansible.builtin.include_tasks: "create-openshift-config.yml"
- ansible.builtin.include_tasks: "validate-ignition-files.yml"
