---

- name: Check status of pull secret file
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/pull-secret"
  register: pull_secret_stat

- name: Verify pull secret file exists
  when: not pull_secret_stat.stat.exists
  ansible.builtin.fail:
    msg: |
      There has to be a pull secret at {{ playbook_dir }}/pull-secret.
      Download secret from https://console.redhat.com/openshift/install/pull-secret
      to {{ playbook_dir }}/pull-secret"

- name: Create pull-secret tmp directory
  ansible.builtin.file:
    state: directory
    path: "{{ openshift_files_directory }}/.pull-secret"
    mode: '0755'

- name: Copy original pull-secret file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/pull-secret"
    dest: "{{ openshift_files_directory }}/.pull-secret/pull-secret.original"
    mode: '0644'

# Docs: https://docs.okd.io/4.11/support/remote_health_monitoring/opting-out-of-remote-health-reporting.html
- name: Opt out of remote health reporting
  when: opt_out_of_remote_health_reporting
  ansible.builtin.shell: >-
    jq -c 'del(.auths."cloud.openshift.com")'
    {{ openshift_files_directory }}/.pull-secret/pull-secret.original > {{ openshift_files_directory }}/.pull-secret/pull-secret.1
  register: host_result
  failed_when: host_result.stderr != ""
  changed_when: false

- name: Copy modified pull-secret file
  ansible.builtin.copy:
    src: "{{ openshift_files_directory }}/.pull-secret/pull-secret.1"
    dest: "{{ openshift_files_directory }}/pull-secret"
    mode: '0644'
