---

- name: Check status of pull secret file
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/pull-secret"
  register: secret

- name: Verify pull secret file exists
  when: not secret.stat.exists
  ansible.builtin.fail:
    msg: |
      there has to be a secret at {{ playbook_dir }}/pull-secret.
      Download secret from https://console.redhat.com/openshift/install/pull-secret
      to {{ playbook_dir }}/pull-secret"

- name: Copy pull secret file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/pull-secret"
    dest: "{{ openshift_files_directory }}/pull-secret"
    mode: '0644'

# Docs: https://docs.okd.io/4.11/support/remote_health_monitoring/opting-out-of-remote-health-reporting.html
- name: Opt out of remote health reporting
  when: opt_out_of_remote_health_reporting
  ansible.builtin.shell: >-
    jq -c 'del(.auths."cloud.openshift.com")'
    {{ openshift_files_directory }}/pull-secret > {{ openshift_files_directory }}/pull-secret.tmp
    && mv {{ openshift_files_directory }}/pull-secret.tmp {{ openshift_files_directory }}/pull-secret
  register: host_result
  failed_when: host_result.stderr != ""
