- name: Find ignition files
  ansible.builtin.find:
    paths: "{{ openshift_files_directory }}"
    patterns: '*.ign'
  register: files

- name: Validate ignition files
  ansible.builtin.command:
    cmd: "{{ openshift_ignition_validate_executable }} {{ item.path }}"
  loop: "{{ files.files }}"
  changed_when: false
