---

- name: Configure UFW to allow access access to tcp ports 80,443,1936,6443,8080,22623
  community.general.ufw:
    rule: allow
    port: "'{{ item }}'"
    proto: tcp
  loop:
    - 80
    - 443
    - 1936
    - 6443
    - 8080
    - 22623
