- name: Remove a number of packages
  apt:
    name: "{{ packages }}"
    state: absent
    autoclean: yes
    autoremove: yes
    purge: yes
  vars:
    packages:
      - android-*
      - apache2
      - apache2-*
      - apertium
      - apertium-*
      - argonaut-*
      - aspell
      - aspell-*
      - asterisk
      - asterisk-*
      - galculator
      - geoip-database
      - libreoffice-*
      - minecraft-pi
      - realvnc-vnc-server
      - realvnc-vnc-viewer
      - scratch
      - scratch2
      - sonic-pi
      - wolfram-engine
