- name: Check unpartitioned space
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      /sbin/parted /dev/mmcblk0 unit gb print free | grep 'Free Space' | tail -n1 | awk '{print $3}'
    args:
      executable: /bin/bash
  register: unpartitioned
  changed_when: false
  failed_when: unpartitioned.stderr != ""

- name: Expand filesystem to fill disk
  ansible.builtin.command: raspi-config --expand-rootfs
  when: unpartitioned.stdout != "0.00GB"

- name: Reboot after file system change
  ansible.builtin.reboot:
  when: unpartitioned.stdout != "0.00GB"
