- name: Wait 300 seconds for target connection to become reachable/usable
  wait_for_connection:
    delay: 0
    timeout: 300

- name: Gathering facts
  setup:

- include_tasks: "expand-file-system.yml"
- include_tasks: "apt.yml"
- include_tasks: "ntp.yml"
