---

- name: Copy over nginx ignition configuration
  ansible.builtin.template:
    src: ignition.conf.j2
    dest: /etc/nginx/sites-enabled/ignition.conf
    mode: '0644'
  notify: Restart nginx

- name: Create ignition file directory
  ansible.builtin.file:
    state: directory
    path: "{{ nginx_ignition_files_dir }}"
    mode: '0755'

- name: Copy over ignition files
  ansible.builtin.copy:
    src: "{{ openshift_files_ignition_directory }}/"
    dest: "{{ nginx_ignition_files_dir }}"
    mode: '0644'

- name: Copy install.sh
  ansible.builtin.template:
    src: install.sh.j2
    dest: "{{ nginx_static_hosting_root_dir }}/install.sh"
    mode: '0644'
