- name: Api-Proxy - Copy over ignition files
  template:
    src: ./openshift-files/{{ item }}.ign
    dest: /usr/share/nginx/html/{{ item }}.{{ cluster_name }}.{{ base_domain }}.ign
  with_items:
    - "bootstrap"
    - "master"
    - "worker"

- name: Api-Proxy - Copy over master ignition files
  template:
    src: ./openshift-files/{{ item }}.ign
    dest: /usr/share/nginx/html/{{ item }}.ign
  loop: "{{ groups['masters'] }}"


- name: Api-Proxy - Copy over worker ignition files
  template:
    src: ./openshift-files/{{ item }}.ign
    dest: /usr/share/nginx/html/{{ item }}.ign
  loop: "{{ groups['nodes'] }}"

- name: Api-Proxy - Copy install.sh
  template:
    src: ./openshift-files/install.sh
    dest: /usr/share/nginx/html/install.sh
