- name: Wait 300 seconds for target connection to become reachable/usable
  wait_for_connection:
    delay: 0
    timeout: 300

- name: Gathering facts
  setup:

- include_tasks: "api-proxy.yml"
- include_tasks: "copy-ignition-files.yml"
