- name: Make ssh dir
  file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0600

- name: tweak ssh
  blockinfile:
    path: /etc/ssh/ssh_config
    block: |
      ServerAliveInterval 240
      ControlMaster auto
      ControlPath ~/.ssh/ssh_mux_%h_%p_%r
      ControlPersist 448h

- name: Set authorized SSH key taken from local file
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '/Users/john/.ssh/id_ansible.pub') }}"
  become: no
