---

- name: Wait for cluster installation to finish
  ansible.builtin.shell:
    cmd: >-
      "{{ openshift_install_executable }}" wait-for install-complete --dir={{ openshift_files_directory }}/
    executable: /bin/bash
  delegate_to: localhost
  register: install_complete
  become: false
  changed_when: false
  until: install_complete.rc == 0
