---
- name: Publish install version as fact
  ansible.builtin.set_fact:
    okd_version_full: "{{ okd_version | regex_search('[0-9]\\.[0-9]+\\.[0-9]+.*') }}"
    okd_version: "{{ okd_version | regex_search('[0-9]\\.[0-9]+\\.[0-9]+') }}"
    okd_version_minor: "{{ okd_version | regex_search('([0-9]+\\.[0-9]+)\\.', '\\1') | first }}"

- name: Wait for cluster installation to finish
  ansible.builtin.shell:
    cmd: >-
      "{{ openshift_install_executable }}" wait-for install-complete --dir={{ openshift_files_directory }}/
    executable: /bin/bash
  delegate_to: localhost
  register: install_complete
  become: false
  changed_when: false
  until: install_complete.rc == 0
  when: okd_version_minor not in ["4.12"]
