apiVersion: v1
baseDomain: {{ base_domain }}
compute:
  - hyperthreading: Enabled
    name: worker
{% if use_control_plane_nodes_for_compute %}
    replicas: 0
{% else %}
    replicas: {{ nrOfNodes }}
{% endif %}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: {{ nrOfMasters }}
metadata:
  name: {{ cluster_name }}
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  none: {}
pullSecret: "{{ pullSecret }}"
sshKey: "{{ sshKey }}"
