apiVersion: v1
baseDomain: example.com
compute:
  - hyperthreading: Enabled
    name: worker
    replicas: {{ nrOfNodes }}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: {{ nrOfMasters }}
metadata:
  name: ocp4
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
platform:
  none: {}
pullSecret: "{{ pullSecret }}"
sshKey: "{{ sshKey }}"
