# Docs: https://docs.openshift.com/container-platform/4.10/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#ipi-install-configuration-files
apiVersion: v1
baseDomain: {{ base_domain }}
compute:
  - hyperthreading: Enabled
    name: worker
{% if use_control_plane_nodes_for_compute %}
    replicas: 0
{% else %}
    replicas: {{ nrOfNodes }}
{% endif %}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: {{ nrOfMasters }}
metadata:
  name: {{ cluster_name }}
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  none: {}
pullSecret: "{{ pullSecret }}"
sshKey: "{{ sshKey }}"
{% if use_disconnected_registry == true %}
additionalTrustBundle: |
  {{ lookup('file', disconnected_registry_trust_bundle_file) | regex_replace('\n', '\n  ') }}
imageContentSources:
  - source: quay.io.openshift
    mirrors:
      - {{ disconnected_registry_url }}
{% endif %}