---

- name: Copy over nginx ignition configuration
  ansible.builtin.template:
    src: ignition.conf
    dest: /etc/nginx/sites-enabled/ignition.conf
  notify: nginx restart

- name: Copy over generic ignition files
  ansible.builtin.copy:
    src: "{{ openshift_files_directory }}/{{ item }}.ign"
    dest: "{{ nginx_ignition_files_dir }}/{{ item }}.ign"
  with_items:
    - "bootstrap"
    - "master"
    - "worker"
  notify: nginx restart

- name: Copy over bootstrap ignition files
  ansible.builtin.copy:
    src: "{{ openshift_files_directory }}/{{ item }}.ign"
    dest: "{{ nginx_ignition_files_dir }}/{{ item }}.ign"
  loop: "{{ groups['bootstrap'] }}"
  notify: nginx restart

- name: Copy over master ignition files
  ansible.builtin.copy:
    src: "{{ openshift_files_directory }}/{{ item }}.ign"
    dest: "{{ nginx_ignition_files_dir }}/{{ item }}.ign"
  loop: "{{ groups['masters'] }}"
  notify: nginx restart

- name: Copy over worker ignition files
  ansible.builtin.copy:
    src: "{{ openshift_files_directory }}/{{ item }}.ign"
    dest: "{{ nginx_ignition_files_dir }}/{{ item }}.ign"
  loop: "{{ groups['nodes'] }}"
  notify: nginx restart

- name: Copy install.sh
  ansible.builtin.copy:
    src: "{{ openshift_files_directory }}/install.sh"
    dest: "{{ nginx_ignition_files_dir }}/install.sh"
  notify: nginx restart
