---
- name: Wait 300 seconds for target connection to become reachable/usable
  ansible.builtin.wait_for_connection:
    delay: 0
    timeout: 300

- name: Gathering facts
  ansible.builtin.setup:

- name: Expand file system
  ansible.builtin.include_tasks: "expand-file-system.yml"

- name: Install packages
  ansible.builtin.include_tasks: "apt.yml"

- name: Setup ntp
  ansible.builtin.include_tasks: "ntp.yml"
