nodes:
  children:
    bootstrap:
    masters:
    workers:
lbs:
  hosts:
    lbs.okd4.local.com:
      vagrant_ip: 172.16.32.90
bootstrap:
  hosts:
    bootstrap.okd4.local.com:
      vagrant_ip: 172.16.32.100
masters:
  hosts:
    master1.okd4.local.com:
      vagrant_ip: 172.16.32.101
    master2.okd4.local.com:
      vagrant_ip: 172.16.32.102
    master3.okd4.local.com:
      vagrant_ip: 172.16.32.103
workers:
  hosts:
    worker1.okd4.local.com:
      vagrant_ip: 172.16.32.111
