---
nodes:
  children:
    bootstrap:
    masters:
    workers:
lbs:
  hosts:
    lbs.okd4.local.com:
      ipv4: 192.168.62.90
bootstrap:
  hosts:
    bootstrap.okd4.local.com:
      ipv4: 192.168.62.100
      mac: '08:00:27:C9:3C:00'
masters:
  hosts:
    master1.okd4.local.com:
      ipv4: 192.168.62.101
      mac: '08:00:27:C9:3C:01'
    master2.okd4.local.com:
      ipv4: 192.168.62.102
      mac: '08:00:27:C9:3C:02'
    master3.okd4.local.com:
      ipv4: 192.168.62.103
      mac: '08:00:27:C9:3C:03'
workers:
  hosts:
    worker1.okd4.local.com:
      ipv4: 192.168.62.111
      mac: '08:00:27:C9:3C:11'
