nodes:
  children:
    bootstrap:
    masters:
    workers:
lbs:
  hosts:
    lbs.okd4.local.com:
      vagrant_ip: 192.168.62.90
bootstrap:
  hosts:
    bootstrap.okd4.local.com:
      vagrant_ip: 192.168.62.100
masters:
  hosts:
    master1.okd4.local.com:
      vagrant_ip: 192.168.62.101
    master2.okd4.local.com:
      vagrant_ip: 192.168.62.102
    master3.okd4.local.com:
      vagrant_ip: 192.168.62.103
workers:
  hosts:
    worker1.okd4.local.com:
      vagrant_ip: 192.168.62.111
