- name: Create local install directory
  ansible.builtin.file:
    state: directory
    path: "{{ openshift_install_directory }}"
    mode: '0755'

- name: Get stats of openshift-install executable
  ansible.builtin.stat:
    path: "{{ openshift_install_executable }}"
  register: st

- name: Define openshift install download url
  ansible.builtin.set_fact:
    openshift_install_download_url: "https://github.com/openshift/okd/releases/download/{{ okd_version }}/openshift-install-{{ okd_tools_arch }}-{{ okd_version }}.tar.gz" # noqa yaml[line-length]
  when: not st.stat.exists

- name: Inform user about download location
  ansible.builtin.debug:
    msg: "Fetching okd installer from {{ openshift_install_download_url }}"
  when: not st.stat.exists

# https://github.com/openshift/okd/releases
# https://amd64.origin.releases.ci.openshift.org/
- name: Download openshift-install
  when: not st.stat.exists
  ansible.builtin.get_url:
    url: "{{ openshift_install_download_url }}"
    dest: "{{ openshift_install_archive }}"
    mode: '0440'

- name: Unpack openshift-install
  when: not st.stat.exists
  ansible.builtin.command:
    # As we're running on mac, we can't use the module as it requires GNU tar.
    cmd: tar -xvf "{{ openshift_install_archive }}" -C "{{ openshift_install_directory }}" # noqa command-instead-of-module

- name: Delete openshift-install
  ansible.builtin.file:
    state: absent
    path: "{{ openshift_install_archive }}"
