- name: Create directory openshift-install
  ansible.builtin.file:
    state: directory
    path: ./openshift-install

- name: Get stats of a file
  ansible.builtin.stat:
    path: ./openshift-install/openshift-install
  register: st

- name: Define openshift install download url
  ansible.builtin.set_fact:
    openshift_install_download_url: "https://github.com/openshift/okd/releases/download/{{ okd_version }}/openshift-install-{{ okd_tools_arch }}-{{ okd_version }}.tar.gz"
  when: not st.stat.exists

- name: Inform user about download location
  ansible.builtin.debug:
    msg: "Fetching okd installer from {{ openshift_install_download_url }}"
  when: not st.stat.exists

# https://github.com/openshift/okd/releases
# https://amd64.origin.releases.ci.openshift.org/
- name: Download openshift-install
  when: not st.stat.exists
  ansible.builtin.get_url:
    url: "{{ openshift_install_download_url }}"
    dest: ./openshift-install.tar.gz
    mode: '0440'

- name: Unpack openshift-install
  when: not st.stat.exists
  ansible.builtin.shell: tar -xvf ./openshift-install.tar.gz -C ./openshift-install

- name: Delete openshift-install
  ansible.builtin.file:
    state: absent
    path: ./openshift-install.tar.gz
