- name: Delete directory {{ openshift_files_directory }}
  ansible.builtin.file:
    state: absent
    path: "{{ openshift_files_directory }}"

- name: Create directory {{ openshift_files_directory }}
  ansible.builtin.file:
    state: directory
    path: "{{ openshift_files_directory }}"
    mode: '0755'

- name: 3. Create installation config
  ansible.builtin.template:
    src: templates/install-config.yaml
    dest: "{{ openshift_files_directory }}/install-config.yaml"
    mode: '0644'

- name: 3. Fetch install version
  ansible.builtin.include_tasks: "get-oc-version.yml"

- name: 3. Create cluster manifests files
  ansible.builtin.shell:
    cmd: "{{ openshift_install_executable }} create manifests --dir={{ openshift_files_directory }}"

- name: 3. Create cluster ignition files
  ansible.builtin.shell:
    cmd: "{{ openshift_install_executable }} create ignition-configs --dir={{ openshift_files_directory }}"

- name: Log oc_version_minor
  ansible.builtin.debug:
    var: oc_version_minor

- name: 3. Fix ignition files
  ansible.builtin.include_tasks: "3.1-fix-ignition-files.yml"
  loop:
    - "bootstrap"
    - "master"
    - "worker"

- name: 3. Fix ignition files v4.8
  ansible.builtin.include_tasks: "3.1-fix-ignition-files-v4.8.yml"
  vars:
    ifname: "eno1"
  loop:
    - "bootstrap"
    - "master"
    - "worker"
  when: oc_version_minor in ["4.8", "4.9"]

- name: 3. Masters - Create host specific ignition files
  ansible.builtin.include_tasks: "3.2-create-host-specific-ignition-file.yml"
  loop: "{{ groups['masters'] }}"
  vars:
    template: master.ign

- name: 3. Workers - Create host specific ignition files
  ansible.builtin.include_tasks: "3.2-create-host-specific-ignition-file.yml"
  loop: "{{ groups['nodes'] }}"
  vars:
    template: worker.ign

- name: 3. Bootstrap - Create host specific ignition files
  ansible.builtin.include_tasks: "3.2-create-host-specific-ignition-file.yml"
  loop: "{{ groups['bootstrap'] }}"
  vars:
    template: bootstrap.ign
