- name: "3.1 {{ item }} - Create the network delay configuration"
  set_fact:
    rendered_template: "{{ lookup('template', 'carrier-wait-timeout.conf') }}"
  register: networkdelay

- debug:
    var: networkdelay

- name: "3.1 {{ item }} - Add the network delay configuration"
  shell: |
    cat openshift-files/{{ item }}.ign \
    | jq '.storage.files += [{"overwrite": true,"path": "/run/NetworkManager/conf.d/delay-{{ ifname }}.conf","mode": 420,"user": {"name": "root"},"contents": {"source": "data:text/plain;charset=utf-8;base64,{{ networkdelay | b64encode }}"}}]' \
    > openshift-files/{{ item }}.json \
    && mv openshift-files/{{ item }}.json openshift-files/{{ item }}.ign
