- name: "3.2 {{ item }} - Create the full hostname"
  set_fact:
    hostname: "{{ item }}.ocp4.example.com"


- name: "3.2 {{ item }} - Prepare the common fixes in {{ item }}.ign file"
  shell: |
    cat openshift-files/{{ template }} \
    | jq '.storage.files += [{"overwrite": true,"path": "/etc/hostname","mode": 420,"user": {"name": "root"},"contents": {"source": "data:text/plain;charset=utf-8;base64,{{ hostname | b64encode }}"}}]' \
    > openshift-files/{{ item }}.json \
    && mv openshift-files/{{ item }}.json openshift-files/{{ item }}.ign
  register: host_result
  failed_when: host_result.stderr != ""
