- name: 2. Fetch install version
  shell: ./openshift-install/openshift-install version | head -1
  delegate_to: localhost
  register: install_version

- name: 2. Publish install version as fact
  set_fact:
    OC_VERSION_FULL: "{{ install_version | regex_search('[0-9]\\.[0-9]+\\.[0-9]+.*') }}"
    OC_VERSION: "{{ install_version | regex_search('[0-9]\\.[0-9]+\\.[0-9]+') }}"
    OC_VERSION_MINOR: "{{ install_version | regex_search('([0-9]+\\.[0-9]+)\\.', '\\1') | first}}"
