---

- name: Pause for starting CoreOS installation on workers
  ansible.builtin.pause:
    prompt: |
      -----------------------------------
      - Do the following on all workers -
      -----------------------------------
      1. Boot CoreOS
      2. Run the following command to install CoreOS:

      bash -c "$(curl -fsSL http://{{ groups['lbs'][0] }}:8080/install.sh)"
      or
      bash -c "$(curl -fsSL http://{{ groups['lbs'][0] }}:8080/install.sh)" -s worker[1-3]

      3. Reboot and verify they are trying to retrieve the second stage ignition file.

      ----------------------------
      - Press return to continue -
      ----------------------------

- name: Enroll workers by approving certificate requests
  ansible.builtin.command:
    cmd: ./issueCertificates.sh "{{ inventory_hostname }}"
  when: inventory_hostname in groups['workers']
  delegate_to: localhost
  register: result
  until: result.rc == 0
  retries: 5000
  delay: 1
  changed_when: false
