name: CI
on:
  pull_request:
  push:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Run ansible-lint
        # https://github.com/ansible-community/ansible-lint-action
        # List of lint rules: https://ansible-lint.readthedocs.io/en/latest/
        uses: ansible-community/ansible-lint-action@v6.2.1
        with:
          path: "./roles"
