---
name: CI
"on":
  pull_request:
  push:
jobs:
  lint:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'  # caching pip dependencies

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          make dependencies

      - name: Lint code
        run: |
          make lint

  molecule:
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Retrieve pull-secret
        run: |
          echo '{"auths":{"fake":{"auth": "Zm9vOmJhcgo="}}}' > pull-secret

      - name: Generate ansible SSH key
        run: |
          ssh-keygen -t ed25519 -C "ansible ssh key" -f ~/.ssh/id_ansible -q -N ''

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'  # caching pip dependencies

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          sudo apt install vagrant virtualbox
          make dependencies

      - name: Test with molecule
        run: |
          make molecule-test
